export const experiences = {
  es: {
    title: "Experiencia",
    list: [
      {
        title: "Desarrollador Fullstack",
        company: "Perla Technology",
        date: "jul. 2022 - dic. 2023",
        img: {
          src: "experience/perla-technology.webp",
          alt: "Perla Technology",
          width: 1081,
          height: 357,
        },
        tasks: [
          "Participar en reuniones para discutir requisitos y progreso del proyecto.",
          "Configurar Firebase para autenticación, base de datos y funciones en la nube.",
          "Convertir la interfaz móvil a una aplicación web usando React.",
          "Integrar la aplicación web con Firebase para autenticación y base de datos.",
          "Identificar y corregir errores durante el desarrollo y las pruebas.",
          "Desplegar la aplicación web en el servicio de hosting de Firebase.",
          "Monitorear el rendimiento, corregir errores y mejorar la aplicación.",
          "Escribir documentación para facilitar la comprensión y mantenimiento del código.",
        ],
      },
      {
        title: "Aprendiz Desarrollador de Software",
        company: "SoftwareOne Colombia",
        date: "abr. 2023 - oct. 2023",
        img: {
          src: "experience/softwareone.webp",
          alt: "SoftwareOne",
          width: 1592,
          height: 560,
        },
        tasks: [
          "Participar en reuniones diarias de Scrum para coordinar tareas.",
          "Revisar y comprender los requisitos del cliente para los nuevos componentes.",
          "Diseñar componentes React basados en los requisitos del cliente.",
          "Escribir código de componentes React con reutilización.",
          "Realizar pruebas unitarias y de integración para los nuevos componentes.",
          "Integrar los nuevos componentes en la aplicación existente.",
          "Revisar el código con el equipo para asegurar calidad y cumplimiento de estándares.",
          "Desplegar y probar los componentes en un entorno de desarrollo.",
          "Participar en reuniones de Sprint Review para presentar los avances al cliente y obtener feedback.",
        ],
      },
    ],
  },
  en: {
    title: "Experience",
    list: [
      {
        title: "Fullstack Developer",
        company: "Perla Technology",
        date: "Jul 2022 - Dec 2023",
        img: {
          src: "experience/perla-technology.webp",
          alt: "Perla Technology",
          width: 1081,
          height: 357,
        },
        tasks: [
          "Participate in meetings to discuss requirements and project progress.",
          "Set up Firebase for authentication, database, and cloud functions.",
          "Convert the mobile interface to a web application using React.",
          "Integrate the web application with Firebase for authentication and database.",
          "Identify and fix bugs during development and testing.",
          "Deploy the web application to Firebase hosting service.",
          "Monitor performance, fix bugs, and improve the application.",
          "Write documentation to facilitate code understanding and maintenance.",
        ],
      },
      {
        title: "Software Developer Apprentice",
        company: "SoftwareOne Colombia",
        date: "Apr 2023 - Oct 2023",
        img: {
          src: "experience/softwareone.webp",
          alt: "SoftwareOne",
          width: 1592,
          height: 560,
        },
        tasks: [
          "Participate in daily Scrum meetings to coordinate tasks.",
          "Review and understand customer requirements for new components.",
          "Design React components based on client requirements.",
          "Write reusable React component code.",
          "Perform unit and integration testing for new components.",
          "Integrate new components into the existing application.",
          "Review code with the team to ensure quality and adherence to standards.",
          "Deploy and test components in a development environment.",
          "Participate in Sprint Review meetings to present progress to the client and obtain feedback.",
        ],
      },
    ],
  },
};
